name = "BioSequenceMappings"
uuid = "a84bc454-70cc-4f51-8a9d-ca76a5a82222"
authors = ["Pierre Barrat-Charlaix"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
